apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-svc
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - protocol: TCP
      name: ingress-nginx-http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: ingress-nginx-https
      port: 443
      targetPort: 443
