apiVersion: skaffold/v2beta17
kind: Config
portForward:
  - resourceType: Service
    resourceName: prometheus-grafana
    port: 80
    localPort: 8888
    namespace: monitoring
  - resourceType: Service
    resourceName: cmak
    port: 9000
    localPort: 9000
    namespace: kafka
deploy:
  helm:
    releases:
      - name: prometheus
        namespace: monitoring
        createNamespace: true
        remoteChart: prometheus-community/kube-prometheus-stack
      - name: kafka
        remoteChart: bitnami/kafka
        namespace: kafka
        createNamespace: true
        setValues:
          replicaCount: 3
          persistence.enabled: false
      - name: cmak
        remoteChart: cmak/cmak-operator
        namespace: kafka
        setValues:
          cmak.clusters[0].name: local-cluster
          cmak.clusters[0].curatorConfig.zkConnect: kafka-zookeeper-headless:2181
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: anhkhoa45/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: anhkhoa45/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: anhkhoa45/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: anhkhoa45/event-bus-test
      context: event-bus-test
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
